language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 stdio.c -o stdio
  - ./stdio
  - gcov stdio.c || cat stdio.c 

after_success:
  - bash <(curl -s https://codecov.io/bash)
