language: c
sudo: false # only for faster builds
script:
  - clang -coverage -O0 string.c -o string
  - ./string
  - gcov string.c || cat string.c 

after_success:
  - bash <(curl -s https://codecov.io/bash)
